name: Release
env:
  PUBLISH_PATH_WIN: '${{ github.workspace }}\publish'
  PUBLISH_PATH_LIN: '${{ github.workspace }}/publish'
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  #VERSION_NUMBER: '$($env:GITHUB_REF -replace "refs/tags/v")'
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  generate:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5           
    - name: Add msbuild to PATH 
      uses: microsoft/setup-msbuild@v1.0.1      
    - name: Restore NuGet packages
      run: nuget restore WallpaperBuddy.sln   
      # create .env file with the secrets
    - name: Attach Environment Variables
      uses: iamsauravsharma/create-dotenv@v1.0.0
      with:      
        env-prefix: 'ENV_KEY_'
        file-name: 'development.env'
        directory: './wallpaperbuddy'
      env: # env available for only this steps        
        ENV_KEY_deviantArtClientId: ${{secrets.DEVIANT_ART_CLIENT_ID}}
        ENV_KEY_deviantArtClientSecret: ${{secrets.DEVIANT_ART_CLIENT_SECRET}}      
    - name: Build
      #run: dotnet build --configuration Release --no-restore -o '${{env.PUBLISH_PATH}}'
      run: msbuild /t:Build /p:DebugSymbols=false /p:DebugType=None /p:OutDir=${{env.PUBLISH_PATH_WIN}}\      
    - name: Upload the Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: wallpaperbuddy
        path: '${{env.PUBLISH_PATH_WIN}}'      
  deploy:
    runs-on: ubuntu-latest
    needs: [generate]
    steps:
    - name: Download the build artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: wallpaperbuddy
        path: '${{env.PUBLISH_PATH_LIN}}'            
    - name: Remove PDB
      run: rm -f ./*.pdb      
    - name: Remove XML
      run: rm -f ./*.xml
    - name: Verify download
      run: ls -al '${{env.PUBLISH_PATH_LIN}}' 
    - name: 'Get last release tag'
        id: releasetag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 
    - name: Prepare package
      run: zip -r -j '${{env.PUBLISH_PATH_LIN}}/wallpaperbuddy-winx64-${{ steps.releasetag.outputs.tag }}.zip' ${{env.PUBLISH_PATH_LIN}}
    - name: Upload the Package to Release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
      with:
        args: '${{env.PUBLISH_PATH_LIN}}/wallpaperbuddy-winx64-${{ steps.releasetag.outputs.tag }}.zip'
